### ISSUE TITLE
Could not generate a proxy class for class

### ISSUE THREAD

**Issue by BenDave** [neworld/gradle-jdeploy-plugin#1]
Hi,

I am getting the following error when applying `gradle-jdeploy-plugin` to my gradle project.
My project is using the same version of gradle as the plugin (4.3.1). Any idea how to fix this would be appreciated - thanks !

```
> Failed to apply plugin [id 'lt.neworld.jdeploy']
   > Could not generate a proxy class for class lt.neworld.gradle.jdeploy.task.JDeployPackageGenerate.
```

**Comment by neworld** [comment]
Hello,

I have some ideas, but I need more info. Are you using kotlin in your project? The stacktrace would be very helpful for me. Could you show it to me?

**Comment by BenDave** [comment]
I Should have used `--stacktrace` before starting this thread, there was as missing dependency which I added and the build now works:
```
Caused by: java.lang.ClassNotFoundException: com.squareup.moshi.Moshi
        ... 132 more
```
btw I don't use kotlin on this project.

It might still be useful to add this dependency to your plugin to avoid this error in the future ..

Thanks for your help !

**Comment by neworld** [comment]
Definitely, it will be, but I [had added it already](https://github.com/neworld/gradle-jdeploy-plugin/blob/master/build.gradle.kts#L22). Also, Gradle should throw an exception about missing dependency in the first place. Could you show your build script?
