### ISSUE TITLE
Version 0.5.1 contain classes compiled with Java 10

### ISSUE THREAD

**Issue by msangel** [neworld/gradle-jdeploy-plugin#3]
This cause the plugin to fail with Java 8
```shell
user@pc:~/Downloads/gradle-jdeploy/gradle-jdeploy-plugin-0.5.1/lt/neworld/gradle/jdeploy/task$ file JDeploySetup.class 
JDeploySetup.class: compiled Java class data, version 54.0
```

Here's also gradle traces:
https://gist.github.com/msangel/0ad823c7a100ed2a96ccbe6aa370daa9

Please compile it with java8 compatibility. Currently this is still most commonly used Java version. 
___
UPD: I used this plugin as [source dependency](https://blog.gradle.org/introducing-source-dependencies) and it successfully compiled under java8. This is fine as a temporary workaround but building this plugin from source as a part of building mine project lifecycle is not ok.

**Comment by neworld** [comment]
Fixed. Will be released with next versions. Thanks! And sorry for long delay
